
images:
  pullPolicy: IfNotPresent

init:
  # By default the installation will not set an explicit one, which will mean it uses `default` for the namespace the chart is
  # being deployed to.  In RBAC clusters, that will almost certainly fail.  See the NOTES: section of the readme for more info.
  serviceAccount: argo-chaos

nameOverride: ${name_override}
fullnameOverride: ${name_override}

workflow:
  namespace: ""  # Specify namespace if workflows run in another namespace than argo. This controls where the service account and RBAC resources will be created.

controller:
  serviceAccount:
    create: true
    name: argo

  name: workflow-controller

  workflowNamespaces:
    - litmus

  logging:
    level: info
    globallevel: "0"

  nodeSelector:
    role: ${tools_logical_role_name}
  tolerations:
    - key: ${tools_logical_role_name}
      operator: "Equal"
      value: "true"
      effect: NoSchedule

server:
  enabled: true
  name: server
  serviceType: ClusterIP
  servicePort: 2746
  # servicePortName: http
  serviceAccount:
    create: true
    name: argo-server

  replicas: 1

  nodeSelector:
    role: ${tools_logical_role_name}
  tolerations:
    - key: ${tools_logical_role_name}
      operator: "Equal"
      value: "true"
      effect: NoSchedule

  ## Ingress configuration.
  ## ref: https://kubernetes.io/docs/user-guide/ingress/
  ##
  ingress:
    # Note: We are creating the Ingress in Terraform rather than here.
    enabled: false




