
nameOverride: ${name_override}
fullnameOverride: ${name_override}

operatorName: "chaos-operator"

replicaCount: 1

operator:
  image:
    repository: litmuschaos/chaos-operator
    tag: 1.13.5
    pullPolicy: IfNotPresent

runner:
  image:
    repository: litmuschaos/chaos-runner
    tag: 1.13.5

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector:
  role: ${tools_logical_role_name}
tolerations:
  - key: ${tools_logical_role_name}
    operator: "Equal"
    value: "true"
    effect: NoSchedule

# Supports: standard, admin, namespaced
operatorMode: admin

# Support for disabling google analytics
# https://docs.litmuschaos.io/docs/faq-general/#does-litmus-track-any-usage-metrics-on-the-test-clusters
policies:
  monitoring:
    disabled: false

exporter:
  enabled: false
  serviceMonitor:
    enabled: false
    additionalLabels: {}
  image:
    repository: litmuschaos/chaos-exporter
    tag: 1.13.5
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    annotations: {}

  resources: {}

  nodeSelector:
    role: ${tools_logical_role_name}
  tolerations:
    - key: ${tools_logical_role_name}
      operator: "Equal"
      value: "true"
      effect: NoSchedule
