
namespace: # defined by the deployment script
clusterName: # defined by the deployment script
awsAccount: # defined by the deployment script

appName: basic

replicaCount: 2

serviceAccount:
  name: basic-service-account

priorityClass:
  name: regular

createDeployment: true

containerPort: 8080

image:
  repository: michaelkubecourse/basic-microservice
  pullPolicy: IfNotPresent

ingress:
  enabled: false

containerHealthChecks:
  readinessProbe:
    failureThreshold: 2
    successThreshold: 1
    httpGet:
      path: /hello
      port: 8080
    initialDelaySeconds: 35
    periodSeconds: 10
    timeoutSeconds: 5
  livenessProbe:
    failureThreshold: 2
    successThreshold: 1
    httpGet:
      path: /hello
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5

resources:
  requests:
    memory: 256M
    cpu: 550m
  limits:
    memory: 256M
    cpu: 600m

horizontalPodAutoscaler:
  enabled: true
  maxReplicas: 6
  minReplicas: 2

helmTest:
  enabled: true
  command: "curl -sS -X GET http://basic.apps.svc.cluster.local:8080/hello?myName=MichaelK"
  expectedCommandResult: "Hello MichaelK!"
